FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["PPMS/PPMS.csproj", "PPMS/"]
RUN dotnet restore "PPMS/PPMS.csproj"
COPY PPMS/ PPMS/
WORKDIR /src/PPMS
RUN dotnet build "PPMS.csproj" -c Release -o /app/build

FROM build AS publish
WORKDIR /src/PPMS
RUN dotnet publish "PPMS.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir -p \
    /app/wwwroot/uploads/profiles \
    /app/wwwroot/uploads/photos \
    /app/wwwroot/uploads/wanted \
    /app/wwwroot/uploads/cases/documents \
    /app/wwwroot/uploads/cases/evidence \
    /app/wwwroot/uploads/staff/photos \
    /app/wwwroot/uploads/staff/certificates \
    /app/wwwroot/uploads/prisoners/evidence \
    /app/wwwroot/images
ENTRYPOINT ["dotnet", "PPMS.dll"]
